
"""
This type stub file was generated by pyright.
"""

from typing import List, Tuple, Union
from PIL import Image

class Color:
    rgb: Tuple[int, int, int]
    hsl: Tuple[float, float, float]
    proportion: float
    
    def __init__(self, rgb: Tuple[int, int, int], proportion: float) -> None: ...

def extract(
    image: Union[str, Image.Image], 
    number_of_colors: int = 6
) -> List[Color]: ...
