
"""
This type stub file was generated by pyright.
"""

import sys
from typing import List, Tuple, Union, Any
from PIL import Image
import numpy as np
from numpy.typing import NDArray

if sys.version_info[0] <= 2:
    ARRAY_DATATYPE: Any = ...
else:
    ARRAY_DATATYPE: Any = ...

Rgb = Tuple[int, int, int]
Hsl = Tuple[float, float, float]

class Color:
    rgb: Rgb
    proportion: float
    
    def __init__(self, r: int, g: int, b: int, proportion: float) -> None: ...
    
    def __repr__(self) -> str: ...
    
    @property
    def hsl(self) -> Hsl: ...

def extract(f: Union[str, Image.Image], number_of_colors: int = 6) -> List[Color]: ...

def sample(image: Image.Image) -> NDArray[np.uint8]: ...

def pick_used(samples: NDArray[np.uint8]) -> List[Tuple[int, int, int]]: ...

def get_colors(samples: NDArray[np.uint8], used: List[Tuple[int, int, int]], number_of_colors: int) -> List[Color]: ...

def hsl(r: int, g: int, b: int) -> Tuple[float, float, float]: ...
